version: '3.8'

services:
  
  web:
    build: .
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    command: gunicorn -c gunicorn.conf.py --worker-class eventlet -w 1 run:app

    volumes:
      - .:/app

